apiVersion: apps/v1
kind: Deployment
metadata:
  name: niral-deployment
  labels:
    app: niralapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: niralapp
  template:
    metadata:
      labels:
        app: niralapp
    spec:
      containers:
      - name: niral-container
        image: niralthinknyx/intel-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: niral-deployment
  spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: niralapp 
